# Generated by Django 5.0.6 on 2025-12-09 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='marcas/')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text='Formato internacional sin + (ej: 5491112345678)', max_length=20)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('mercado_libre_url', models.URLField(blank=True, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('horarios', models.TextField(blank=True, help_text='Ej: Lunes a Viernes de 9 a 18hs', null=True)),
                ('logo_sitio', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#000000', help_text='Hex code (ej: #FF00FF)', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion_corta', models.CharField(max_length=255)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('imagen_principal', models.ImageField(upload_to='productos/')),
                ('es_destacado', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('url_mercado_libre', models.URLField(blank=True, help_text='Link al producto en ML. Si está vacío, se usará el de SiteConfig.', null=True)),
                ('url_instagram', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='productos', to='catalogo.categoriaproducto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.marca')),
            ],
            options={
                'ordering': ['orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['orden'],
            },
        ),
    ]
