# Generated by Django 5.0.6 on 2025-12-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_stock',
            field=models.BooleanField(default=True, help_text='Desmarcar si el producto está sin stock', verbose_name='Tiene Stock'),
        ),
    ]
