# Generated by Django 5.0.6 on 2025-12-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_add_tiene_stock_to_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_sitio_2',
            field=models.ImageField(blank=True, help_text='Logo de cuenta asociada (se mostrará al lado del principal)', null=True, upload_to='site/', verbose_name='Logo Secundario'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_sitio',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo Principal'),
        ),
    ]
